### ISSUE TITLE
ReadTimeout during capture

### ISSUE THREAD

**Issue by lluchiari** [pierremolinaro/can20B-plugin-for-saleae-logic-analyzer#1]
During free running execution, it's giving "ReadTimeout" error after about 600ms

![ErrorLog](https://user-images.githubusercontent.com/12159740/117706038-2f859000-b1a3-11eb-8bac-8da57edac53d.png)

**Comment by pierremolinaro** [comment]
Hello,

I have tested the plugin only with Logic, never with Logic2. So there is probably an incompatibility, or I made a mistake that went unnoticed with Logic2.

I'm not home until Friday, so I won't be able to look into this bug until then. I'll let you know as soon as I've fixed it.

Pierre

**Comment by pierremolinaro** [comment]
Sorry, bit I can't reproduce your error. What are your settings ? What is your Logic2 version ?
